version: '3.8'

services:
  app:
    build:
      context: .
    environment:
      DATABASE_HOST: postgres.c9um0i6uafzi.us-east-2.rds.amazonaws.com
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: postgres4321
      JWT_SECRET: secret_key_api_node
    ports:
      ["3000:3000"]
          